/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as CreateIndexRouteImport } from "./routes/create.index";
import { Route as CreateCustomRouteImport } from "./routes/create.custom";
import { Route as CreateMappingsRouteImport } from "./routes/create.mappings";
import { Route as CreateNfcRouteImport } from "./routes/create.nfc";
import { Route as CreateSearchRouteImport } from "./routes/create.search";
import { Route as CreateTextRouteImport } from "./routes/create.text";
import { Route as LibraryIndexRouteImport } from "./routes/library.index";
import { Route as LibrarySystemRouteImport } from "./routes/library.$system";
import { Route as LibraryDislikedRouteImport } from "./routes/library.disliked";
import { Route as LibraryFavoritesRouteImport } from "./routes/library.favorites";
import { Route as LibraryLikedRouteImport } from "./routes/library.liked";
import { Route as LibraryPlayLaterRouteImport } from "./routes/library.play-later";
import { Route as LibrarySearchRouteImport } from "./routes/library.search";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as SettingsAboutRouteImport } from "./routes/settings.about";
import { Route as SettingsAccessibilityRouteImport } from "./routes/settings.accessibility";
import { Route as SettingsAdvancedRouteImport } from "./routes/settings.advanced";
import { Route as SettingsDevicesRouteImport } from "./routes/settings.devices";
import { Route as SettingsHelpRouteImport } from "./routes/settings.help";
import { Route as SettingsLanguageRegionRouteImport } from "./routes/settings.language-region";
import { Route as SettingsLicensesRouteImport } from "./routes/settings.licenses";
import { Route as SettingsLogsRouteImport } from "./routes/settings.logs";
import { Route as SettingsMediaRouteImport } from "./routes/settings.media";
import { Route as SettingsOnlineRouteImport } from "./routes/settings.online";
import { Route as SettingsPlayControlsRouteImport } from "./routes/settings.play-controls";
import { Route as SettingsReadersRouteImport } from "./routes/settings.readers";
import { Route as CreateDecksNewRouteImport } from "./routes/create.decks.new";
import { Route as CreateMappingsNewRouteImport } from "./routes/create.mappings_.new";
import { Route as LibraryDecksDeckIdRouteImport } from "./routes/library.decks.$deckId";
import { Route as LibraryDecksNewRouteImport } from "./routes/library.decks.new";
import { Route as SettingsDevicesRecordIdRouteImport } from "./routes/settings.devices_.$recordId";
import { Route as CreateMappingsEditIdRouteImport } from "./routes/create.mappings_.edit_.$id";
import { Route as LibraryDecksDeckIdAddRouteImport } from "./routes/library.decks.$deckId_.add";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateCustomRoute = CreateCustomRouteImport.update({
  id: "/create/custom",
  path: "/create/custom",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsRoute = CreateMappingsRouteImport.update({
  id: "/create/mappings",
  path: "/create/mappings",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateNfcRoute = CreateNfcRouteImport.update({
  id: "/create/nfc",
  path: "/create/nfc",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateSearchRoute = CreateSearchRouteImport.update({
  id: "/create/search",
  path: "/create/search",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateTextRoute = CreateTextRouteImport.update({
  id: "/create/text",
  path: "/create/text",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: "/library/",
  path: "/library/",
  getParentRoute: () => rootRouteImport,
} as any);
const LibrarySystemRoute = LibrarySystemRouteImport.update({
  id: "/library/$system",
  path: "/library/$system",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryDislikedRoute = LibraryDislikedRouteImport.update({
  id: "/library/disliked",
  path: "/library/disliked",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryFavoritesRoute = LibraryFavoritesRouteImport.update({
  id: "/library/favorites",
  path: "/library/favorites",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryLikedRoute = LibraryLikedRouteImport.update({
  id: "/library/liked",
  path: "/library/liked",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryPlayLaterRoute = LibraryPlayLaterRouteImport.update({
  id: "/library/play-later",
  path: "/library/play-later",
  getParentRoute: () => rootRouteImport,
} as any);
const LibrarySearchRoute = LibrarySearchRouteImport.update({
  id: "/library/search",
  path: "/library/search",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/settings/about",
  path: "/settings/about",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: "/settings/accessibility",
  path: "/settings/accessibility",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: "/settings/advanced",
  path: "/settings/advanced",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: "/settings/devices",
  path: "/settings/devices",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: "/settings/help",
  path: "/settings/help",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsLanguageRegionRoute = SettingsLanguageRegionRouteImport.update({
  id: "/settings/language-region",
  path: "/settings/language-region",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsLicensesRoute = SettingsLicensesRouteImport.update({
  id: "/settings/licenses",
  path: "/settings/licenses",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: "/settings/logs",
  path: "/settings/logs",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsMediaRoute = SettingsMediaRouteImport.update({
  id: "/settings/media",
  path: "/settings/media",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsOnlineRoute = SettingsOnlineRouteImport.update({
  id: "/settings/online",
  path: "/settings/online",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsPlayControlsRoute = SettingsPlayControlsRouteImport.update({
  id: "/settings/play-controls",
  path: "/settings/play-controls",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsReadersRoute = SettingsReadersRouteImport.update({
  id: "/settings/readers",
  path: "/settings/readers",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateDecksNewRoute = CreateDecksNewRouteImport.update({
  id: "/create/decks/new",
  path: "/create/decks/new",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsNewRoute = CreateMappingsNewRouteImport.update({
  id: "/create/mappings_/new",
  path: "/create/mappings/new",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryDecksDeckIdRoute = LibraryDecksDeckIdRouteImport.update({
  id: "/library/decks/$deckId",
  path: "/library/decks/$deckId",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryDecksNewRoute = LibraryDecksNewRouteImport.update({
  id: "/library/decks/new",
  path: "/library/decks/new",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsDevicesRecordIdRoute = SettingsDevicesRecordIdRouteImport.update({
  id: "/settings/devices_/$recordId",
  path: "/settings/devices/$recordId",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsEditIdRoute = CreateMappingsEditIdRouteImport.update({
  id: "/create/mappings_/edit_/$id",
  path: "/create/mappings/edit/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const LibraryDecksDeckIdAddRoute = LibraryDecksDeckIdAddRouteImport.update({
  id: "/library/decks/$deckId_/add",
  path: "/library/decks/$deckId/add",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/library/$system": typeof LibrarySystemRoute;
  "/library/disliked": typeof LibraryDislikedRoute;
  "/library/favorites": typeof LibraryFavoritesRoute;
  "/library/liked": typeof LibraryLikedRoute;
  "/library/play-later": typeof LibraryPlayLaterRoute;
  "/library/search": typeof LibrarySearchRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/language-region": typeof SettingsLanguageRegionRoute;
  "/settings/licenses": typeof SettingsLicensesRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/media": typeof SettingsMediaRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/create/": typeof CreateIndexRoute;
  "/library/": typeof LibraryIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/create/decks/new": typeof CreateDecksNewRoute;
  "/create/mappings/new": typeof CreateMappingsNewRoute;
  "/library/decks/$deckId": typeof LibraryDecksDeckIdRoute;
  "/library/decks/new": typeof LibraryDecksNewRoute;
  "/settings/devices/$recordId": typeof SettingsDevicesRecordIdRoute;
  "/create/mappings/edit/$id": typeof CreateMappingsEditIdRoute;
  "/library/decks/$deckId/add": typeof LibraryDecksDeckIdAddRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/library/$system": typeof LibrarySystemRoute;
  "/library/disliked": typeof LibraryDislikedRoute;
  "/library/favorites": typeof LibraryFavoritesRoute;
  "/library/liked": typeof LibraryLikedRoute;
  "/library/play-later": typeof LibraryPlayLaterRoute;
  "/library/search": typeof LibrarySearchRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/language-region": typeof SettingsLanguageRegionRoute;
  "/settings/licenses": typeof SettingsLicensesRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/media": typeof SettingsMediaRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/create": typeof CreateIndexRoute;
  "/library": typeof LibraryIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/create/decks/new": typeof CreateDecksNewRoute;
  "/create/mappings/new": typeof CreateMappingsNewRoute;
  "/library/decks/$deckId": typeof LibraryDecksDeckIdRoute;
  "/library/decks/new": typeof LibraryDecksNewRoute;
  "/settings/devices/$recordId": typeof SettingsDevicesRecordIdRoute;
  "/create/mappings/edit/$id": typeof CreateMappingsEditIdRoute;
  "/library/decks/$deckId/add": typeof LibraryDecksDeckIdAddRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/library/$system": typeof LibrarySystemRoute;
  "/library/disliked": typeof LibraryDislikedRoute;
  "/library/favorites": typeof LibraryFavoritesRoute;
  "/library/liked": typeof LibraryLikedRoute;
  "/library/play-later": typeof LibraryPlayLaterRoute;
  "/library/search": typeof LibrarySearchRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/language-region": typeof SettingsLanguageRegionRoute;
  "/settings/licenses": typeof SettingsLicensesRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/media": typeof SettingsMediaRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/create/": typeof CreateIndexRoute;
  "/library/": typeof LibraryIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/create/decks/new": typeof CreateDecksNewRoute;
  "/create/mappings_/new": typeof CreateMappingsNewRoute;
  "/library/decks/$deckId": typeof LibraryDecksDeckIdRoute;
  "/library/decks/new": typeof LibraryDecksNewRoute;
  "/settings/devices_/$recordId": typeof SettingsDevicesRecordIdRoute;
  "/create/mappings_/edit_/$id": typeof CreateMappingsEditIdRoute;
  "/library/decks/$deckId_/add": typeof LibraryDecksDeckIdAddRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/library/$system"
    | "/library/disliked"
    | "/library/favorites"
    | "/library/liked"
    | "/library/play-later"
    | "/library/search"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/language-region"
    | "/settings/licenses"
    | "/settings/logs"
    | "/settings/media"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/create/"
    | "/library/"
    | "/settings/"
    | "/create/decks/new"
    | "/create/mappings/new"
    | "/library/decks/$deckId"
    | "/library/decks/new"
    | "/settings/devices/$recordId"
    | "/create/mappings/edit/$id"
    | "/library/decks/$deckId/add";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/library/$system"
    | "/library/disliked"
    | "/library/favorites"
    | "/library/liked"
    | "/library/play-later"
    | "/library/search"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/language-region"
    | "/settings/licenses"
    | "/settings/logs"
    | "/settings/media"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/create"
    | "/library"
    | "/settings"
    | "/create/decks/new"
    | "/create/mappings/new"
    | "/library/decks/$deckId"
    | "/library/decks/new"
    | "/settings/devices/$recordId"
    | "/create/mappings/edit/$id"
    | "/library/decks/$deckId/add";
  id:
    | "__root__"
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/library/$system"
    | "/library/disliked"
    | "/library/favorites"
    | "/library/liked"
    | "/library/play-later"
    | "/library/search"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/language-region"
    | "/settings/licenses"
    | "/settings/logs"
    | "/settings/media"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/create/"
    | "/library/"
    | "/settings/"
    | "/create/decks/new"
    | "/create/mappings_/new"
    | "/library/decks/$deckId"
    | "/library/decks/new"
    | "/settings/devices_/$recordId"
    | "/create/mappings_/edit_/$id"
    | "/library/decks/$deckId_/add";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreateCustomRoute: typeof CreateCustomRoute;
  CreateMappingsRoute: typeof CreateMappingsRoute;
  CreateNfcRoute: typeof CreateNfcRoute;
  CreateSearchRoute: typeof CreateSearchRoute;
  CreateTextRoute: typeof CreateTextRoute;
  LibrarySystemRoute: typeof LibrarySystemRoute;
  LibraryDislikedRoute: typeof LibraryDislikedRoute;
  LibraryFavoritesRoute: typeof LibraryFavoritesRoute;
  LibraryLikedRoute: typeof LibraryLikedRoute;
  LibraryPlayLaterRoute: typeof LibraryPlayLaterRoute;
  LibrarySearchRoute: typeof LibrarySearchRoute;
  SettingsAboutRoute: typeof SettingsAboutRoute;
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute;
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute;
  SettingsDevicesRoute: typeof SettingsDevicesRoute;
  SettingsHelpRoute: typeof SettingsHelpRoute;
  SettingsLanguageRegionRoute: typeof SettingsLanguageRegionRoute;
  SettingsLicensesRoute: typeof SettingsLicensesRoute;
  SettingsLogsRoute: typeof SettingsLogsRoute;
  SettingsMediaRoute: typeof SettingsMediaRoute;
  SettingsOnlineRoute: typeof SettingsOnlineRoute;
  SettingsPlayControlsRoute: typeof SettingsPlayControlsRoute;
  SettingsReadersRoute: typeof SettingsReadersRoute;
  CreateIndexRoute: typeof CreateIndexRoute;
  LibraryIndexRoute: typeof LibraryIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  CreateDecksNewRoute: typeof CreateDecksNewRoute;
  CreateMappingsNewRoute: typeof CreateMappingsNewRoute;
  LibraryDecksDeckIdRoute: typeof LibraryDecksDeckIdRoute;
  LibraryDecksNewRoute: typeof LibraryDecksNewRoute;
  SettingsDevicesRecordIdRoute: typeof SettingsDevicesRecordIdRoute;
  CreateMappingsEditIdRoute: typeof CreateMappingsEditIdRoute;
  LibraryDecksDeckIdAddRoute: typeof LibraryDecksDeckIdAddRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/": {
      id: "/create/";
      path: "/create";
      fullPath: "/create/";
      preLoaderRoute: typeof CreateIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/custom": {
      id: "/create/custom";
      path: "/create/custom";
      fullPath: "/create/custom";
      preLoaderRoute: typeof CreateCustomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings": {
      id: "/create/mappings";
      path: "/create/mappings";
      fullPath: "/create/mappings";
      preLoaderRoute: typeof CreateMappingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/nfc": {
      id: "/create/nfc";
      path: "/create/nfc";
      fullPath: "/create/nfc";
      preLoaderRoute: typeof CreateNfcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/search": {
      id: "/create/search";
      path: "/create/search";
      fullPath: "/create/search";
      preLoaderRoute: typeof CreateSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/text": {
      id: "/create/text";
      path: "/create/text";
      fullPath: "/create/text";
      preLoaderRoute: typeof CreateTextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/": {
      id: "/library/";
      path: "/library";
      fullPath: "/library/";
      preLoaderRoute: typeof LibraryIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/$system": {
      id: "/library/$system";
      path: "/library/$system";
      fullPath: "/library/$system";
      preLoaderRoute: typeof LibrarySystemRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/disliked": {
      id: "/library/disliked";
      path: "/library/disliked";
      fullPath: "/library/disliked";
      preLoaderRoute: typeof LibraryDislikedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/favorites": {
      id: "/library/favorites";
      path: "/library/favorites";
      fullPath: "/library/favorites";
      preLoaderRoute: typeof LibraryFavoritesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/liked": {
      id: "/library/liked";
      path: "/library/liked";
      fullPath: "/library/liked";
      preLoaderRoute: typeof LibraryLikedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/play-later": {
      id: "/library/play-later";
      path: "/library/play-later";
      fullPath: "/library/play-later";
      preLoaderRoute: typeof LibraryPlayLaterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/search": {
      id: "/library/search";
      path: "/library/search";
      fullPath: "/library/search";
      preLoaderRoute: typeof LibrarySearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/about": {
      id: "/settings/about";
      path: "/settings/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof SettingsAboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/accessibility": {
      id: "/settings/accessibility";
      path: "/settings/accessibility";
      fullPath: "/settings/accessibility";
      preLoaderRoute: typeof SettingsAccessibilityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/advanced": {
      id: "/settings/advanced";
      path: "/settings/advanced";
      fullPath: "/settings/advanced";
      preLoaderRoute: typeof SettingsAdvancedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/devices": {
      id: "/settings/devices";
      path: "/settings/devices";
      fullPath: "/settings/devices";
      preLoaderRoute: typeof SettingsDevicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/help": {
      id: "/settings/help";
      path: "/settings/help";
      fullPath: "/settings/help";
      preLoaderRoute: typeof SettingsHelpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/language-region": {
      id: "/settings/language-region";
      path: "/settings/language-region";
      fullPath: "/settings/language-region";
      preLoaderRoute: typeof SettingsLanguageRegionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/licenses": {
      id: "/settings/licenses";
      path: "/settings/licenses";
      fullPath: "/settings/licenses";
      preLoaderRoute: typeof SettingsLicensesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/logs": {
      id: "/settings/logs";
      path: "/settings/logs";
      fullPath: "/settings/logs";
      preLoaderRoute: typeof SettingsLogsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/media": {
      id: "/settings/media";
      path: "/settings/media";
      fullPath: "/settings/media";
      preLoaderRoute: typeof SettingsMediaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/online": {
      id: "/settings/online";
      path: "/settings/online";
      fullPath: "/settings/online";
      preLoaderRoute: typeof SettingsOnlineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/play-controls": {
      id: "/settings/play-controls";
      path: "/settings/play-controls";
      fullPath: "/settings/play-controls";
      preLoaderRoute: typeof SettingsPlayControlsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/readers": {
      id: "/settings/readers";
      path: "/settings/readers";
      fullPath: "/settings/readers";
      preLoaderRoute: typeof SettingsReadersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/decks/new": {
      id: "/create/decks/new";
      path: "/create/decks/new";
      fullPath: "/create/decks/new";
      preLoaderRoute: typeof CreateDecksNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings_/new": {
      id: "/create/mappings_/new";
      path: "/create/mappings/new";
      fullPath: "/create/mappings/new";
      preLoaderRoute: typeof CreateMappingsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/decks/$deckId": {
      id: "/library/decks/$deckId";
      path: "/library/decks/$deckId";
      fullPath: "/library/decks/$deckId";
      preLoaderRoute: typeof LibraryDecksDeckIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/decks/new": {
      id: "/library/decks/new";
      path: "/library/decks/new";
      fullPath: "/library/decks/new";
      preLoaderRoute: typeof LibraryDecksNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/devices_/$recordId": {
      id: "/settings/devices_/$recordId";
      path: "/settings/devices/$recordId";
      fullPath: "/settings/devices/$recordId";
      preLoaderRoute: typeof SettingsDevicesRecordIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings_/edit_/$id": {
      id: "/create/mappings_/edit_/$id";
      path: "/create/mappings/edit/$id";
      fullPath: "/create/mappings/edit/$id";
      preLoaderRoute: typeof CreateMappingsEditIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/library/decks/$deckId_/add": {
      id: "/library/decks/$deckId_/add";
      path: "/library/decks/$deckId/add";
      fullPath: "/library/decks/$deckId/add";
      preLoaderRoute: typeof LibraryDecksDeckIdAddRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCustomRoute: CreateCustomRoute,
  CreateMappingsRoute: CreateMappingsRoute,
  CreateNfcRoute: CreateNfcRoute,
  CreateSearchRoute: CreateSearchRoute,
  CreateTextRoute: CreateTextRoute,
  LibrarySystemRoute: LibrarySystemRoute,
  LibraryDislikedRoute: LibraryDislikedRoute,
  LibraryFavoritesRoute: LibraryFavoritesRoute,
  LibraryLikedRoute: LibraryLikedRoute,
  LibraryPlayLaterRoute: LibraryPlayLaterRoute,
  LibrarySearchRoute: LibrarySearchRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsLanguageRegionRoute: SettingsLanguageRegionRoute,
  SettingsLicensesRoute: SettingsLicensesRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMediaRoute: SettingsMediaRoute,
  SettingsOnlineRoute: SettingsOnlineRoute,
  SettingsPlayControlsRoute: SettingsPlayControlsRoute,
  SettingsReadersRoute: SettingsReadersRoute,
  CreateIndexRoute: CreateIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CreateDecksNewRoute: CreateDecksNewRoute,
  CreateMappingsNewRoute: CreateMappingsNewRoute,
  LibraryDecksDeckIdRoute: LibraryDecksDeckIdRoute,
  LibraryDecksNewRoute: LibraryDecksNewRoute,
  SettingsDevicesRecordIdRoute: SettingsDevicesRecordIdRoute,
  CreateMappingsEditIdRoute: CreateMappingsEditIdRoute,
  LibraryDecksDeckIdAddRoute: LibraryDecksDeckIdAddRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
