/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings.index";
import { Route as CreateIndexRouteImport } from "./routes/create.index";
import { Route as SettingsScraperRouteImport } from "./routes/settings.scraper";
import { Route as SettingsReadersRouteImport } from "./routes/settings.readers";
import { Route as SettingsPlayControlsRouteImport } from "./routes/settings.play-controls";
import { Route as SettingsOnlineRouteImport } from "./routes/settings.online";
import { Route as SettingsLogsRouteImport } from "./routes/settings.logs";
import { Route as SettingsHelpRouteImport } from "./routes/settings.help";
import { Route as SettingsDevicesRouteImport } from "./routes/settings.devices";
import { Route as SettingsAdvancedRouteImport } from "./routes/settings.advanced";
import { Route as SettingsAccessibilityRouteImport } from "./routes/settings.accessibility";
import { Route as SettingsAboutRouteImport } from "./routes/settings.about";
import { Route as CreateTextRouteImport } from "./routes/create.text";
import { Route as CreateSearchRouteImport } from "./routes/create.search";
import { Route as CreateNfcRouteImport } from "./routes/create.nfc";
import { Route as CreateMappingsRouteImport } from "./routes/create.mappings";
import { Route as CreateCustomRouteImport } from "./routes/create.custom";
import { Route as SettingsDevicesAddressRouteImport } from "./routes/settings.devices_.$address";
import { Route as CreateMappingsNewRouteImport } from "./routes/create.mappings_.new";
import { Route as CreateMappingsEditIdRouteImport } from "./routes/create.mappings_.edit_.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsScraperRoute = SettingsScraperRouteImport.update({
  id: "/settings/scraper",
  path: "/settings/scraper",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsReadersRoute = SettingsReadersRouteImport.update({
  id: "/settings/readers",
  path: "/settings/readers",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsPlayControlsRoute = SettingsPlayControlsRouteImport.update({
  id: "/settings/play-controls",
  path: "/settings/play-controls",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsOnlineRoute = SettingsOnlineRouteImport.update({
  id: "/settings/online",
  path: "/settings/online",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: "/settings/logs",
  path: "/settings/logs",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: "/settings/help",
  path: "/settings/help",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: "/settings/devices",
  path: "/settings/devices",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: "/settings/advanced",
  path: "/settings/advanced",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAccessibilityRoute = SettingsAccessibilityRouteImport.update({
  id: "/settings/accessibility",
  path: "/settings/accessibility",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: "/settings/about",
  path: "/settings/about",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateTextRoute = CreateTextRouteImport.update({
  id: "/create/text",
  path: "/create/text",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateSearchRoute = CreateSearchRouteImport.update({
  id: "/create/search",
  path: "/create/search",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateNfcRoute = CreateNfcRouteImport.update({
  id: "/create/nfc",
  path: "/create/nfc",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsRoute = CreateMappingsRouteImport.update({
  id: "/create/mappings",
  path: "/create/mappings",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateCustomRoute = CreateCustomRouteImport.update({
  id: "/create/custom",
  path: "/create/custom",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsDevicesAddressRoute = SettingsDevicesAddressRouteImport.update({
  id: "/settings/devices_/$address",
  path: "/settings/devices/$address",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsNewRoute = CreateMappingsNewRouteImport.update({
  id: "/create/mappings_/new",
  path: "/create/mappings/new",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateMappingsEditIdRoute = CreateMappingsEditIdRouteImport.update({
  id: "/create/mappings_/edit_/$id",
  path: "/create/mappings/edit/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/settings/scraper": typeof SettingsScraperRoute;
  "/create/": typeof CreateIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/create/mappings/new": typeof CreateMappingsNewRoute;
  "/settings/devices/$address": typeof SettingsDevicesAddressRoute;
  "/create/mappings/edit/$id": typeof CreateMappingsEditIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/settings/scraper": typeof SettingsScraperRoute;
  "/create": typeof CreateIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/create/mappings/new": typeof CreateMappingsNewRoute;
  "/settings/devices/$address": typeof SettingsDevicesAddressRoute;
  "/create/mappings/edit/$id": typeof CreateMappingsEditIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/create/custom": typeof CreateCustomRoute;
  "/create/mappings": typeof CreateMappingsRoute;
  "/create/nfc": typeof CreateNfcRoute;
  "/create/search": typeof CreateSearchRoute;
  "/create/text": typeof CreateTextRoute;
  "/settings/about": typeof SettingsAboutRoute;
  "/settings/accessibility": typeof SettingsAccessibilityRoute;
  "/settings/advanced": typeof SettingsAdvancedRoute;
  "/settings/devices": typeof SettingsDevicesRoute;
  "/settings/help": typeof SettingsHelpRoute;
  "/settings/logs": typeof SettingsLogsRoute;
  "/settings/online": typeof SettingsOnlineRoute;
  "/settings/play-controls": typeof SettingsPlayControlsRoute;
  "/settings/readers": typeof SettingsReadersRoute;
  "/settings/scraper": typeof SettingsScraperRoute;
  "/create/": typeof CreateIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/create/mappings_/new": typeof CreateMappingsNewRoute;
  "/settings/devices_/$address": typeof SettingsDevicesAddressRoute;
  "/create/mappings_/edit_/$id": typeof CreateMappingsEditIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/logs"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/settings/scraper"
    | "/create/"
    | "/settings/"
    | "/create/mappings/new"
    | "/settings/devices/$address"
    | "/create/mappings/edit/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/logs"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/settings/scraper"
    | "/create"
    | "/settings"
    | "/create/mappings/new"
    | "/settings/devices/$address"
    | "/create/mappings/edit/$id";
  id:
    | "__root__"
    | "/"
    | "/create/custom"
    | "/create/mappings"
    | "/create/nfc"
    | "/create/search"
    | "/create/text"
    | "/settings/about"
    | "/settings/accessibility"
    | "/settings/advanced"
    | "/settings/devices"
    | "/settings/help"
    | "/settings/logs"
    | "/settings/online"
    | "/settings/play-controls"
    | "/settings/readers"
    | "/settings/scraper"
    | "/create/"
    | "/settings/"
    | "/create/mappings_/new"
    | "/settings/devices_/$address"
    | "/create/mappings_/edit_/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreateCustomRoute: typeof CreateCustomRoute;
  CreateMappingsRoute: typeof CreateMappingsRoute;
  CreateNfcRoute: typeof CreateNfcRoute;
  CreateSearchRoute: typeof CreateSearchRoute;
  CreateTextRoute: typeof CreateTextRoute;
  SettingsAboutRoute: typeof SettingsAboutRoute;
  SettingsAccessibilityRoute: typeof SettingsAccessibilityRoute;
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute;
  SettingsDevicesRoute: typeof SettingsDevicesRoute;
  SettingsHelpRoute: typeof SettingsHelpRoute;
  SettingsLogsRoute: typeof SettingsLogsRoute;
  SettingsOnlineRoute: typeof SettingsOnlineRoute;
  SettingsPlayControlsRoute: typeof SettingsPlayControlsRoute;
  SettingsReadersRoute: typeof SettingsReadersRoute;
  SettingsScraperRoute: typeof SettingsScraperRoute;
  CreateIndexRoute: typeof CreateIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  CreateMappingsNewRoute: typeof CreateMappingsNewRoute;
  SettingsDevicesAddressRoute: typeof SettingsDevicesAddressRoute;
  CreateMappingsEditIdRoute: typeof CreateMappingsEditIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/": {
      id: "/create/";
      path: "/create";
      fullPath: "/create/";
      preLoaderRoute: typeof CreateIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/scraper": {
      id: "/settings/scraper";
      path: "/settings/scraper";
      fullPath: "/settings/scraper";
      preLoaderRoute: typeof SettingsScraperRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/readers": {
      id: "/settings/readers";
      path: "/settings/readers";
      fullPath: "/settings/readers";
      preLoaderRoute: typeof SettingsReadersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/play-controls": {
      id: "/settings/play-controls";
      path: "/settings/play-controls";
      fullPath: "/settings/play-controls";
      preLoaderRoute: typeof SettingsPlayControlsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/online": {
      id: "/settings/online";
      path: "/settings/online";
      fullPath: "/settings/online";
      preLoaderRoute: typeof SettingsOnlineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/logs": {
      id: "/settings/logs";
      path: "/settings/logs";
      fullPath: "/settings/logs";
      preLoaderRoute: typeof SettingsLogsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/help": {
      id: "/settings/help";
      path: "/settings/help";
      fullPath: "/settings/help";
      preLoaderRoute: typeof SettingsHelpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/devices": {
      id: "/settings/devices";
      path: "/settings/devices";
      fullPath: "/settings/devices";
      preLoaderRoute: typeof SettingsDevicesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/advanced": {
      id: "/settings/advanced";
      path: "/settings/advanced";
      fullPath: "/settings/advanced";
      preLoaderRoute: typeof SettingsAdvancedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/accessibility": {
      id: "/settings/accessibility";
      path: "/settings/accessibility";
      fullPath: "/settings/accessibility";
      preLoaderRoute: typeof SettingsAccessibilityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/about": {
      id: "/settings/about";
      path: "/settings/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof SettingsAboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/text": {
      id: "/create/text";
      path: "/create/text";
      fullPath: "/create/text";
      preLoaderRoute: typeof CreateTextRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/search": {
      id: "/create/search";
      path: "/create/search";
      fullPath: "/create/search";
      preLoaderRoute: typeof CreateSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/nfc": {
      id: "/create/nfc";
      path: "/create/nfc";
      fullPath: "/create/nfc";
      preLoaderRoute: typeof CreateNfcRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings": {
      id: "/create/mappings";
      path: "/create/mappings";
      fullPath: "/create/mappings";
      preLoaderRoute: typeof CreateMappingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/custom": {
      id: "/create/custom";
      path: "/create/custom";
      fullPath: "/create/custom";
      preLoaderRoute: typeof CreateCustomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/devices_/$address": {
      id: "/settings/devices_/$address";
      path: "/settings/devices/$address";
      fullPath: "/settings/devices/$address";
      preLoaderRoute: typeof SettingsDevicesAddressRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings_/new": {
      id: "/create/mappings_/new";
      path: "/create/mappings/new";
      fullPath: "/create/mappings/new";
      preLoaderRoute: typeof CreateMappingsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create/mappings_/edit_/$id": {
      id: "/create/mappings_/edit_/$id";
      path: "/create/mappings/edit/$id";
      fullPath: "/create/mappings/edit/$id";
      preLoaderRoute: typeof CreateMappingsEditIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCustomRoute: CreateCustomRoute,
  CreateMappingsRoute: CreateMappingsRoute,
  CreateNfcRoute: CreateNfcRoute,
  CreateSearchRoute: CreateSearchRoute,
  CreateTextRoute: CreateTextRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccessibilityRoute: SettingsAccessibilityRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsOnlineRoute: SettingsOnlineRoute,
  SettingsPlayControlsRoute: SettingsPlayControlsRoute,
  SettingsReadersRoute: SettingsReadersRoute,
  SettingsScraperRoute: SettingsScraperRoute,
  CreateIndexRoute: CreateIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CreateMappingsNewRoute: CreateMappingsNewRoute,
  SettingsDevicesAddressRoute: SettingsDevicesAddressRoute,
  CreateMappingsEditIdRoute: CreateMappingsEditIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
