name: Build Zaparoo web app

on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Authenticate NPM registry
        run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}\n@capawesome-team:registry=https://npm.pkg.github.com/" > ~/.npmrc
      - name: Add Firebase credentials
        run: echo '${{ secrets.FIREBASE_CREDS }}' > ./src/firebase.json
      - name: Install dependencies
        run: npm install
      - name: Production build
        env:
          VITE_VERSION: ${{ github.ref_name }}
          VITE_GOOGLE_STORE_API: ${{ secrets.VITE_GOOGLE_STORE_API }}
          VITE_APPLE_STORE_API: ${{ secrets.VITE_APPLE_STORE_API }}
        run: npm run build

      - name: Package release tarball
        if: startsWith(github.ref, 'refs/tags/')
        run: tar czvf zaparoo-app_web.tar.gz -C ./dist .
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: zaparoo-app_web.tar.gz
          fail_on_unmatched_files: true
          make_latest: false

permissions:
  contents: write
